---
title: ""
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
>Publications

Wright, J. L., Bomfim, B.,Wong, C. I., Marimon-Júnior, B. H., Marimon, B. S., & Silva, L. C. R. (2020). Sixteen hundred years of increasing tree cover prior to modern deforestation in Southern Amazon and Central Brazilian savannas. Global Change Biology, 1-33. https://doi.org/10.1111/gcb.15382

Silva, L. C. R., Corrêa, R. S., Wright, J. L., Bomfim, B., Hendrix, L., & Gavin, D. G. (2021). A New Hypothesis for the Origin of Amazonian Dark Earths. Nature Communications, 12(1). https://doi.org/10.1038/s41467-020-20184-2

National Science Foundation (NSF) Landscape Carbon Sequestration for Atmospheric Recovery White Paper: A Perspective on Convergence to Accelerate Carbon Sequestration. University of Oregon,Eugene, Oregon. [Silva LCR, Wood M, Johnson B, Bomfim B, Coughlan M, Smith M, Brinton H, Bridgham S, and McGuire K (eds.)] 2019.

>Conferences

Woody densification and expansion detected in Brazil using carbon stable isotopes in soil (44th New Phytologist Symposium; 2019)

Forest Expansion Detected in Brazil Using Carbon Stable Isotopes in Soil (Ecological Society of America; 2018)

>Undergraduate Research

Immediate effects of controlled fire on forest soil carbon pools in Brazilian Amazonia (Capstone Research;2016)
