install.packages("config")
library(config)
config::get()
getwd()
setwd("/Users/jamiewright/Documents/GitHub/jamiew12.github.io")
getwd()
setwd("~/Documents/GitHub/jamiew12.github.io/")
blogdown::serve_site()
blogdown::hugo_build()
blogdown::new_post(title, ext = '.md')
blogdown::check_site()
getwd()
blogdown::serve_site(.site_dir = "site")
